version: '3.8'
services:
  firstms:
    container_name: firstms
    image: windflaw8/first_ms
    build:
      context: ./pr6_first-microservice
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - secondms
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://51.250.26.59:5432/appealapp
  secondms:
    container_name: secondms
    image: windflaw8/second_ms
    build:
      context: ./pr6_second-microservice
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    #depends_on:
      #- db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://51.250.26.59:5432/appealapp
  #db:
    #image: postgres:14.7-alpine
    #ports:
      #- 5433:5432
    #environment:
      #POSTGRES_USER: secUREusER
      #POSTGRES_PASSWORD: StrongEnoughPassword)
