server:
  port: 9000
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: users
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: appeals
          uri: lb://APPEALSERVICE
          predicates:
            - Path=/appeals/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-microservice-realm
          jwk-set-uri: http://localhost:8080/realms/spring-microservice-realm/protocol/openid-connect/certs
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: TRACE


