server:
  port: 9000
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: users
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
        - id: appeals
          uri: http://localhost:8081
          predicates:
            - Path=/appeals/**

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


