# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push-to-dh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: pulling
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
              version: v0.7.0

      # Runs a single command using the runners shell
      - name: docker-compose build
        run: docker-compose build
        
      - name: docker login
        uses: docker/login-action@v3.0.0
        with: 
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: pushing
        run: docker-compose push
        
  build-and-push-to-yc:
    runs-on: ubuntu-latest
    steps:
      - name: pulling
        uses: actions/checkout@v3
              
      - name: docker-compose build
        run: docker build -t cr.yandex/${{secrets.YC_REGISTRY_ID }}/appeal-app .

      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
          
      - name: pushing
        run: docker push cr.yandex/${{secrets.YC_REGISTRY_ID }}/appeal-app:latest
      
